### ISSUE TITLE
i forgot adc :( :( :(

### ISSUE THREAD

**Issue by Champers5000** [lhr-solar/BPS-PeripheralSOMPCB#4]
ADC pins need to be connected to the connector

**Comment by Lakshay983** [comment]
As per Data Aq's request, we'll turn pins 4 and 2 into ADC pins
![image](https://github.com/lhr-solar/BPS-PeripheralSOMPCB/assets/56173382/d39958ba-119b-487e-85be-3ba43c7195e6)

**Comment by Lakshay983** [comment]
Nvm i lied it's pins 18 and 20

**Comment by Lakshay983** [comment]
Resolved in #5
